### ISSUE TITLE
[lektor] Remover código do lektor

### ISSUE THREAD

**Issue by daneoshiga** [grupyrp/grupyrp.github.io#6]
O branch acabou indo com o código do lektor em si junto, e o setup do site ficou numa pasta 'GrupyRP'.
- [ ] Remover o código do lektor
- [ ] mover o conteúdo da pasta 'GrupyRP' para a raiz do repositório.

@juhhcarmona você pode fazer isso?

**Comment by juhhcarmona** [comment]
Faço sim @daneoshiga 👍
